version: '3.8'
services:
  dev-db:
    image: postgres:16
    ports:
      - 5450:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pirin
    networks: 
      - pirin
  test-db:
    image: postgres:16
    ports:
      - 5451:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pirin
    networks: 
      - pirin
networks: 
  pirin:
